/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo.login;

public class App {

    public static void main(String[] args) {
        System.out.println("Registrando 5 usuários: ");
        Register.addUser(new User("Bernardo", "123"));
        Register.addUser(new User("Alice", "456"));
        Register.addUser(new User("Carlos", "789"));
        Register.addUser(new User("Diana", "abc"));
        Register.addUser(new User("Eduardo", "def"));
        Register.addUser(new User("BERnardo", "123"));
   

        System.out.println("\nAutenticando o usuário Bernardo, Alice e Carlos : ");
        Register.autenticationUser("Bernardo", "123");
        Register.autenticationUser("Alice", "456");
        Register.autenticationUser("Carlos", "ffff");


        System.out.println("\nListando os usuários cadastrados: ");
        Register.getUsers();
        
        System.out.println("\nRemovendo o usuário Bernardo.. ");
        Register.removeUser("Bernardo");

        System.out.println("\nListando os usuários cadastrados após a remoção do usuário Bernardo: ");
        Register.getUsers();

           
       
    }
}
