/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo.login;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int option;
        String continuar, login, senha;

        while(true){
        System.out.println("Seja bem vindo! \nEscolha uma opção abaixo: \n\n1- Cadastrar um novo usuário\n2- Remover um usuário\n3- Listar todos os usuários cadastrados\n4- Autenticar um usuário\n5- Sair");
        option = sc.nextInt();
        sc.nextLine();

        switch(option){
            case 1:

                do{
                    System.out.print("Digite o login do usuário: ");
                    login =  sc.nextLine();
                    System.out.print("Digite a senha: ");
                    senha = sc.nextLine();

                    new User(login, senha);

                    System.out.println("Deseja cadastrar mais um usuário? (s/n) ");
                    continuar = sc.nextLine().toLowerCase();
                }while (continuar.equals("s"));
                sc.nextLine();
                break;
            case 2:
            do{
                    System.out.print("Digite o login do usuário que deseja remover: ");
                    login =  sc.nextLine();

                    User.removeUser(login);

                    System.out.println("Deseja remover mais um usuário? (s/n) ");
                    continuar = sc.nextLine().toLowerCase();
                }while (continuar.equals("s"));
                sc.nextLine();
                break;
            case 3:
            System.out.println("\n\nLista de usuários: ");
                User.getLogins();
                System.out.println("");
                break;
            case 4:

             do{
                    System.out.print("Digite o login do usuário: ");
                    login =  sc.nextLine();
                    System.out.print("Digite a senha: ");
                    senha = sc.nextLine();

                    User.autenticationUser(login, senha);   

                    System.out.println("Deseja autenticar mais um usuário? (s/n) ");
                    continuar = sc.nextLine().toLowerCase();
                }while (continuar.equals("s"));
                sc.nextLine();
                break;
            case 5:
             sc.close();
            System.out.println("Finalizando programa!");
            return;
        }
        }
       
       
    }
}
